name: Ruby

on: [push, pull_request]

jobs:
  build:
    name: "Ruby ${{ matrix.ruby }}"

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ["2.7", "3.0", "3.1", "3.2", "3.3", "3.4"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby ${{ matrix.ruby }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Build and test with Rake
      run: |
        sudo apt-get update -qq
        sudo apt-get install -yqq python3-sphinx
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake
